/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SummonersIndexRouteImport } from './routes/summoners/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ChampionsIndexRouteImport } from './routes/champions/index'
import { Route as SummonersSummonerNameTagRouteImport } from './routes/summoners/$summonerNameTag'
import { Route as ChampionsChampionIdRouteImport } from './routes/champions/$championId'
import { Route as SessionsViewSessionIdRouteImport } from './routes/sessions/view/$sessionId'
import { Route as SessionsEditSessionIdRouteImport } from './routes/sessions/edit/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummonersIndexRoute = SummonersIndexRouteImport.update({
  id: '/summoners/',
  path: '/summoners/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsIndexRoute = ChampionsIndexRouteImport.update({
  id: '/champions/',
  path: '/champions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummonersSummonerNameTagRoute =
  SummonersSummonerNameTagRouteImport.update({
    id: '/summoners/$summonerNameTag',
    path: '/summoners/$summonerNameTag',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChampionsChampionIdRoute = ChampionsChampionIdRouteImport.update({
  id: '/champions/$championId',
  path: '/champions/$championId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsViewSessionIdRoute = SessionsViewSessionIdRouteImport.update({
  id: '/sessions/view/$sessionId',
  path: '/sessions/view/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsEditSessionIdRoute = SessionsEditSessionIdRouteImport.update({
  id: '/sessions/edit/$sessionId',
  path: '/sessions/edit/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/summoners/$summonerNameTag': typeof SummonersSummonerNameTagRoute
  '/champions': typeof ChampionsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/summoners': typeof SummonersIndexRoute
  '/sessions/edit/$sessionId': typeof SessionsEditSessionIdRoute
  '/sessions/view/$sessionId': typeof SessionsViewSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/summoners/$summonerNameTag': typeof SummonersSummonerNameTagRoute
  '/champions': typeof ChampionsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/summoners': typeof SummonersIndexRoute
  '/sessions/edit/$sessionId': typeof SessionsEditSessionIdRoute
  '/sessions/view/$sessionId': typeof SessionsViewSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/champions/$championId': typeof ChampionsChampionIdRoute
  '/summoners/$summonerNameTag': typeof SummonersSummonerNameTagRoute
  '/champions/': typeof ChampionsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/summoners/': typeof SummonersIndexRoute
  '/sessions/edit/$sessionId': typeof SessionsEditSessionIdRoute
  '/sessions/view/$sessionId': typeof SessionsViewSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/champions/$championId'
    | '/summoners/$summonerNameTag'
    | '/champions'
    | '/sessions'
    | '/summoners'
    | '/sessions/edit/$sessionId'
    | '/sessions/view/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/champions/$championId'
    | '/summoners/$summonerNameTag'
    | '/champions'
    | '/sessions'
    | '/summoners'
    | '/sessions/edit/$sessionId'
    | '/sessions/view/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/champions/$championId'
    | '/summoners/$summonerNameTag'
    | '/champions/'
    | '/sessions/'
    | '/summoners/'
    | '/sessions/edit/$sessionId'
    | '/sessions/view/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionsChampionIdRoute: typeof ChampionsChampionIdRoute
  SummonersSummonerNameTagRoute: typeof SummonersSummonerNameTagRoute
  ChampionsIndexRoute: typeof ChampionsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SummonersIndexRoute: typeof SummonersIndexRoute
  SessionsEditSessionIdRoute: typeof SessionsEditSessionIdRoute
  SessionsViewSessionIdRoute: typeof SessionsViewSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summoners/': {
      id: '/summoners/'
      path: '/summoners'
      fullPath: '/summoners'
      preLoaderRoute: typeof SummonersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions/': {
      id: '/champions/'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summoners/$summonerNameTag': {
      id: '/summoners/$summonerNameTag'
      path: '/summoners/$summonerNameTag'
      fullPath: '/summoners/$summonerNameTag'
      preLoaderRoute: typeof SummonersSummonerNameTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions/$championId': {
      id: '/champions/$championId'
      path: '/champions/$championId'
      fullPath: '/champions/$championId'
      preLoaderRoute: typeof ChampionsChampionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/view/$sessionId': {
      id: '/sessions/view/$sessionId'
      path: '/sessions/view/$sessionId'
      fullPath: '/sessions/view/$sessionId'
      preLoaderRoute: typeof SessionsViewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/edit/$sessionId': {
      id: '/sessions/edit/$sessionId'
      path: '/sessions/edit/$sessionId'
      fullPath: '/sessions/edit/$sessionId'
      preLoaderRoute: typeof SessionsEditSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionsChampionIdRoute: ChampionsChampionIdRoute,
  SummonersSummonerNameTagRoute: SummonersSummonerNameTagRoute,
  ChampionsIndexRoute: ChampionsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SummonersIndexRoute: SummonersIndexRoute,
  SessionsEditSessionIdRoute: SessionsEditSessionIdRoute,
  SessionsViewSessionIdRoute: SessionsViewSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
